Description: >
  CloudFormation stacks for Parley
  Author: Jamie Buckley
Resources:
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/infrastructure.parley.abstractmechanics.co.uk/cluster.yaml
      Parameters:
        Subnets: "subnet-898120f3, subnet-91a2c7f8, subnet-b56b9ff9"
