Description: >
  CloudFormation stacks for Parley
  Author: Jamie Buckley
Resources:
  PipelineRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: pipeline-roles.yaml
  ParleyFrontendPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: frontend-pipeline.yaml
      Parameters:
        PipelineRole: !GetAtt PipelineRoles.Outputs.PipelineRole
